import "./globals.css";
import { Inter } from "next/font/google";
import { ReactQueryProvider } from "./ReactQueryProvider";
import NextAuthProvider from "@components/NextAuthProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/options";
// import Navbar from "@components/SideNavBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Great Run Dashboard",
  // description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)
  // console.log({session})
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <main>
            <NextAuthProvider session={session}>
              {/* <Navbar/> */}
            {children}
            </NextAuthProvider>
            </main>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
